/** Canvas layout presets — positions are % of canvas width/height */

export const TEMPLATE_CATEGORIES = [
  { id: 'all', label: 'All Templates' },
  { id: 'social', label: 'Social' },
  { id: 'ads', label: 'Ads' },
  { id: 'story', label: 'Story' },
  { id: 'promo', label: 'Promo' },
  { id: 'professional', label: 'Professional' },
]

export const BUILTIN_TEMPLATES = [
  {
    id: 'centered-hero',
    name: 'Centered Hero',
    description: 'Bold centered headline with CTA — great for announcements',
    category: 'social',
    recommendedDimension: '1080x1080',
    previewColors: ['#FF6B9D', '#C44DFF'],
    sampleCopy: {
      headline: 'Launch Something Bold',
      subheadline: 'Turn your message into scroll-stopping creative',
      cta: 'Get Started',
      layout: 'centered',
    },
    placements: {
      badge: { x: 0.04, y: 0.04, width: 0.22 },
      headline: { x: 0.08, y: 0.32, width: 0.84, align: 'center', fontSize: 52 },
      subheadline: { x: 0.1, y: 0.48, width: 0.8, align: 'center', fontSize: 22 },
      cta: { x: 0.32, y: 0.72, width: 0.36 },
    },
  },
  {
    id: 'split-left',
    name: 'Split Left',
    description: 'Copy aligned left with room for product imagery on the right',
    category: 'social',
    recommendedDimension: '1080x1080',
    previewColors: ['#4DA8EE', '#1A2B48'],
    sampleCopy: {
      headline: 'Design That Converts',
      subheadline: 'Built for feeds, stories, and paid social',
      cta: 'Shop Now',
      layout: 'split',
    },
    decorElements: [
      { id: 'accent-block', type: 'shape', x: 0.62, y: 0.18, width: 0.32, height: 0.64, fill: 'rgba(255,255,255,0.12)', borderRadius: 24 },
    ],
    placements: {
      badge: { x: 0.05, y: 0.05, width: 0.2 },
      headline: { x: 0.05, y: 0.28, width: 0.55, align: 'left', fontSize: 44 },
      subheadline: { x: 0.05, y: 0.5, width: 0.5, align: 'left', fontSize: 20 },
      cta: { x: 0.05, y: 0.78, width: 0.3 },
    },
  },
  {
    id: 'bottom-stack',
    name: 'Bottom Stack',
    description: 'Headline anchored to the bottom — ideal over photos',
    category: 'social',
    recommendedDimension: '1080x1350',
    previewColors: ['#1A2B48', '#4DA8EE'],
    sampleCopy: {
      headline: 'Your Brand Story',
      subheadline: 'Lead with emotion, close with action',
      cta: 'Learn More',
      layout: 'grid',
    },
    placements: {
      badge: { x: 0.05, y: 0.05, width: 0.2 },
      headline: { x: 0.05, y: 0.58, width: 0.9, align: 'left', fontSize: 40 },
      subheadline: { x: 0.05, y: 0.72, width: 0.85, align: 'left', fontSize: 18 },
      cta: { x: 0.05, y: 0.86, width: 0.28 },
    },
  },
  {
    id: 'minimal-top',
    name: 'Minimal Top',
    description: 'Clean headline at top with open space below',
    category: 'professional',
    recommendedDimension: '1080x1080',
    previewColors: ['#F4F6FB', '#1A2B48'],
    sampleCopy: {
      headline: 'Less Noise. More Impact.',
      subheadline: 'A refined layout for premium brands',
      cta: 'Explore',
      layout: 'minimal',
    },
    placements: {
      badge: { x: 0.05, y: 0.06, width: 0.18 },
      headline: { x: 0.05, y: 0.14, width: 0.9, align: 'left', fontSize: 48 },
      subheadline: { x: 0.05, y: 0.28, width: 0.7, align: 'left', fontSize: 20 },
      cta: { x: 0.05, y: 0.88, width: 0.25 },
    },
    textOnLight: true,
  },
  {
    id: 'story-vertical',
    name: 'Story Vertical',
    description: '9:16 story layout with centered copy stack',
    category: 'story',
    recommendedDimension: '1080x1920',
    previewColors: ['#FF6B9D', '#FF9472'],
    sampleCopy: {
      headline: 'Swipe Up',
      subheadline: 'Limited-time offer ends tonight',
      cta: 'Tap to Shop',
      layout: 'story',
    },
    placements: {
      badge: { x: 0.05, y: 0.08, width: 0.25 },
      headline: { x: 0.06, y: 0.38, width: 0.88, align: 'center', fontSize: 46 },
      subheadline: { x: 0.08, y: 0.52, width: 0.84, align: 'center', fontSize: 20 },
      cta: { x: 0.2, y: 0.78, width: 0.6 },
    },
  },
  {
    id: 'ad-bold',
    name: 'Ad Bold',
    description: 'High-contrast paid social layout with prominent CTA',
    category: 'ads',
    recommendedDimension: '1080x1080',
    previewColors: ['#FF3D71', '#1A2B48'],
    sampleCopy: {
      headline: 'Stop the Scroll',
      subheadline: 'Performance creative for Meta & Google',
      cta: 'Claim Offer',
      layout: 'ad',
    },
    placements: {
      badge: { x: 0.04, y: 0.04, width: 0.24 },
      headline: { x: 0.05, y: 0.2, width: 0.9, align: 'left', fontSize: 56 },
      subheadline: { x: 0.05, y: 0.42, width: 0.75, align: 'left', fontSize: 22 },
      cta: { x: 0.55, y: 0.75, width: 0.38 },
    },
  },
  {
    id: 'quote-card',
    name: 'Quote Card',
    description: 'Share testimonials, tips, or thought leadership quotes',
    category: 'professional',
    recommendedDimension: '1080x1080',
    previewColors: ['#6C5CE7', '#A29BFE'],
    sampleCopy: {
      headline: '"Creativity is intelligence having fun."',
      subheadline: '— Albert Einstein',
      cta: '',
      layout: 'quote',
    },
    placements: {
      badge: { x: 0.05, y: 0.05, width: 0.2 },
      headline: { x: 0.08, y: 0.3, width: 0.84, align: 'center', fontSize: 38 },
      subheadline: { x: 0.1, y: 0.62, width: 0.8, align: 'center', fontSize: 20 },
      cta: { x: 0.35, y: 0.82, width: 0.3 },
    },
  },
  {
    id: 'flash-sale',
    name: 'Flash Sale',
    description: 'Urgent promo layout for discounts and limited drops',
    category: 'promo',
    recommendedDimension: '1080x1080',
    previewColors: ['#FF6B35', '#FFD23F'],
    sampleCopy: {
      headline: '40% OFF',
      subheadline: 'Ends Sunday — free shipping included',
      cta: 'Shop the Sale',
      layout: 'sale',
    },
    decorElements: [
      { id: 'burst', type: 'shape', x: 0.04, y: 0.12, width: 0.42, height: 0.42, fill: 'rgba(255,255,255,0.18)', borderRadius: 999 },
    ],
    placements: {
      badge: { x: 0.05, y: 0.05, width: 0.28 },
      headline: { x: 0.06, y: 0.22, width: 0.88, align: 'left', fontSize: 72 },
      subheadline: { x: 0.06, y: 0.52, width: 0.8, align: 'left', fontSize: 22 },
      cta: { x: 0.06, y: 0.78, width: 0.42 },
    },
  },
  {
    id: 'event-promo',
    name: 'Event Promo',
    description: 'Webinars, launches, and live event announcements',
    category: 'promo',
    recommendedDimension: '1200x628',
    previewColors: ['#00B894', '#00CEC9'],
    sampleCopy: {
      headline: 'Live Workshop',
      subheadline: 'Thursday 2 PM · Register free',
      cta: 'Save My Spot',
      layout: 'event',
    },
    placements: {
      badge: { x: 0.04, y: 0.08, width: 0.22 },
      headline: { x: 0.05, y: 0.24, width: 0.55, align: 'left', fontSize: 48 },
      subheadline: { x: 0.05, y: 0.58, width: 0.5, align: 'left', fontSize: 20 },
      cta: { x: 0.05, y: 0.72, width: 0.32 },
    },
    decorElements: [
      { id: 'date-block', type: 'shape', x: 0.68, y: 0.18, width: 0.26, height: 0.64, fill: 'rgba(255,255,255,0.15)', borderRadius: 16 },
    ],
  },
  {
    id: 'linkedin-post',
    name: 'LinkedIn Post',
    description: 'Professional feed graphic with clear hierarchy',
    category: 'professional',
    recommendedDimension: '1200x628',
    previewColors: ['#0A66C2', '#1A2B48'],
    sampleCopy: {
      headline: '3 Trends Shaping B2B Marketing',
      subheadline: 'What leaders are doing differently this quarter',
      cta: 'Read More',
      layout: 'linkedin',
    },
    placements: {
      badge: { x: 0.04, y: 0.1, width: 0.2 },
      headline: { x: 0.05, y: 0.22, width: 0.9, align: 'left', fontSize: 42 },
      subheadline: { x: 0.05, y: 0.55, width: 0.75, align: 'left', fontSize: 20 },
      cta: { x: 0.05, y: 0.74, width: 0.26 },
    },
  },
  {
    id: 'carousel-slide',
    name: 'Carousel Slide',
    description: 'Numbered slide for Instagram & LinkedIn carousels',
    category: 'social',
    recommendedDimension: '1080x1080',
    previewColors: ['#FD79A8', '#E84393'],
    sampleCopy: {
      headline: 'Tip #1',
      subheadline: 'Hook your audience in the first line',
      cta: 'Swipe →',
      layout: 'carousel',
    },
    decorElements: [
      { id: 'slide-num', type: 'shape', x: 0.78, y: 0.06, width: 0.16, height: 0.16, fill: 'rgba(255,255,255,0.25)', borderRadius: 999 },
    ],
    placements: {
      badge: { x: 0.05, y: 0.05, width: 0.22 },
      headline: { x: 0.05, y: 0.18, width: 0.7, align: 'left', fontSize: 56 },
      subheadline: { x: 0.05, y: 0.42, width: 0.85, align: 'left', fontSize: 24 },
      cta: { x: 0.05, y: 0.82, width: 0.28 },
    },
  },
  {
    id: 'youtube-thumb',
    name: 'YouTube Thumbnail',
    description: 'Bold thumbnail layout for video covers',
    category: 'ads',
    recommendedDimension: '1920x1080',
    previewColors: ['#E74C3C', '#F39C12'],
    sampleCopy: {
      headline: 'WATCH THIS',
      subheadline: 'Before you post again',
      cta: '',
      layout: 'thumbnail',
    },
    decorElements: [
      { id: 'thumb-bar', type: 'shape', x: 0, y: 0.72, width: 1, height: 0.28, fill: 'rgba(0,0,0,0.55)', borderRadius: 0 },
    ],
    placements: {
      badge: { x: 0.03, y: 0.06, width: 0.18 },
      headline: { x: 0.04, y: 0.76, width: 0.92, align: 'left', fontSize: 64 },
      subheadline: { x: 0.04, y: 0.58, width: 0.6, align: 'left', fontSize: 28 },
      cta: { x: 0.04, y: 0.88, width: 0.2 },
    },
  },
  {
    id: 'newsletter-header',
    name: 'Newsletter Header',
    description: 'Email hero banner and blog featured image',
    category: 'professional',
    recommendedDimension: '1200x628',
    previewColors: ['#2D3436', '#636E72'],
    sampleCopy: {
      headline: 'The Weekly Brief',
      subheadline: 'Insights, templates, and tactics — in your inbox',
      cta: 'Subscribe',
      layout: 'newsletter',
    },
    placements: {
      badge: { x: 0.05, y: 0.12, width: 0.24 },
      headline: { x: 0.05, y: 0.28, width: 0.9, align: 'left', fontSize: 46 },
      subheadline: { x: 0.05, y: 0.52, width: 0.7, align: 'left', fontSize: 20 },
      cta: { x: 0.05, y: 0.7, width: 0.28 },
    },
  },
  {
    id: 'product-spotlight',
    name: 'Product Spotlight',
    description: 'Showcase a product with headline and price CTA',
    category: 'promo',
    recommendedDimension: '1080x1350',
    previewColors: ['#A29BFE', '#6C5CE7'],
    sampleCopy: {
      headline: 'New Arrival',
      subheadline: 'Premium quality · Ships free',
      cta: 'Buy Now — $49',
      layout: 'product',
    },
    decorElements: [
      { id: 'product-frame', type: 'shape', x: 0.1, y: 0.14, width: 0.8, height: 0.42, fill: 'rgba(255,255,255,0.14)', borderRadius: 20 },
    ],
    placements: {
      badge: { x: 0.05, y: 0.05, width: 0.22 },
      headline: { x: 0.05, y: 0.6, width: 0.9, align: 'left', fontSize: 44 },
      subheadline: { x: 0.05, y: 0.72, width: 0.85, align: 'left', fontSize: 20 },
      cta: { x: 0.05, y: 0.86, width: 0.4 },
    },
  },
]

export const LAYOUT_TO_TEMPLATE = {
  centered: 'centered-hero',
  split: 'split-left',
  grid: 'bottom-stack',
  hero: 'centered-hero',
  minimal: 'minimal-top',
  story: 'story-vertical',
  ad: 'ad-bold',
  quote: 'quote-card',
  sale: 'flash-sale',
  event: 'event-promo',
  linkedin: 'linkedin-post',
  carousel: 'carousel-slide',
  thumbnail: 'youtube-thumb',
  newsletter: 'newsletter-header',
  product: 'product-spotlight',
}
